make desktop, Html, jar, android, sincronizar, limpar:

desktop:
	./gradlew lwjgl3:run --warning-mode all

Html:
	./gradlew html:superDev

jar:
	./gradlew lwjgl3:dist

android:
	./gradlew android:assembleRelease

sincronizar:
	./gradlew build